"""second

Revision ID: 142dc75a3940
Revises: 42686e9299c8
Create Date: 2023-07-11 22:13:43.247451

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "142dc75a3940"
down_revision = "42686e9299c8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
